version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql-loja
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: loja
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3307:3306"
    volumes:
      - ./dados:/var/lib/mysql
